config/routes.rb
Requestmailer::Application.routes.draw do
  resources :messages
  root :to => 'messages#new'

end

app/models/message.rb
class Message
  include ActiveAttr::Model
  
  attribute :name
  attribute :email
  attribute :comments
  attribute :checkin
  attribute :checkout
  attribute :hood
  attribute :guests
  attribute :rooms
  attribute :country

  attr_accessible :checkin, :checkout, :comments, :country, :email, :guests, :hood, :name, :rooms

  validates_presence_of :name
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_length_of :comments, :maximum => 500
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      UserMailer.request_confirmation(@message).deliver
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Requestmailer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :checkin %><br />
    <%= f.date_select :checkin %>
  </div>
  <div class="field">
    <%= f.label :checkout %><br />
    <%= f.date_select :checkout %>
  </div>
  <div class="field">
    <%= f.label :guests %><br />
    <%= f.number_field :guests %>
  </div>
  <div class="field">
    <%= f.label :rooms %><br />
    <%= f.number_field :rooms %>
  </div>
  <div class="field">
    <%= f.label :hood %><br />
    <%= f.text_field :hood %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/new.html.erb
<h1>Nueva Consulta</h1>

<%= render 'form' %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @message.name %>
</p>

<p>
  <b>Email:</b>
  <%= @message.email %>
</p>

<p>
  <b>Country:</b>
  <%= @message.country %>
</p>

<p>
  <b>Checkin:</b>
  <%= @message.checkin %>
</p>

<p>
  <b>Checkout:</b>
  <%= @message.checkout %>
</p>

<p>
  <b>Guests:</b>
  <%= @message.guests %>
</p>

<p>
  <b>Rooms:</b>
  <%= @message.rooms %>
</p>

<p>
  <b>Hood:</b>
  <%= @message.hood %>
</p>

<p>
  <b>Comments:</b>
  <%= @message.comments %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>